"""Scan every UD treebank this project knows about and list the languages
that have NEITHER any morphological feature annotation in UD NOR any
UniMorph (UM) coverage at all.

These are the languages for which "% covered by UM" / "% covered by UM+UD"
can only ever read 0% -- not because of a bug (like the Akkadian/Assyrian
langcode collision, or the underscore/space langcode-resolution gap), but
because there is genuinely no source of inflectional data for them
anywhere in this project's resources: the UD treebank's tokens carry no
`feats` at all (so the UD-derived UniMorph-schema fallback table is
necessarily empty -- see multiblimp.ud2um.create_unimorph_from_ud), and
there's no proper UniMorph entry for the language either.

Usage (from repo root or scripts/):
    python find_no_coverage_langs.py

Writes resources/langs_no_feats_no_um.txt.
"""
import os
import sys

sys.path.append("../src")
# __file__-based (not CWD-relative): multiblimp.unimorph needs the repo root
# on sys.path too (for `resources.um2ud_annotation`), and a plain "../src"
# only resolves right if this script happens to be run from scripts/ itself.
_repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.append(os.path.join(_repo_root, "src"))
sys.path.append(_repo_root)

from tqdm import tqdm

from multiblimp.languages import get_ud_langs, lang2langcode
from multiblimp.treebank import Treebank


def treebank_has_feature_annotation(treebank) -> bool:
    """True as soon as a single token anywhere in the treebank carries a
    non-empty `feats` dict. Mirrors the exact condition
    multiblimp.ud2um.create_unimorph_from_ud drops tokens on
    (`if len(token_feats) == 0: continue`) -- a treebank where this is
    False for every token is one create_unimorph_from_ud can never produce
    a single UM-schema row from, no matter what else about it changes."""
    for tree in treebank:
        for token in tree:
            if token.get("feats"):
                return True
    return False


def has_um_coverage(langcode: str, resource_dir: str) -> bool:
    """True if resources/unimorph/<langcode> (the proper, non-UD-derived
    UniMorph resource) exists at all for this language."""
    return os.path.exists(os.path.join(resource_dir, "unimorph", langcode))


def main():
    resource_dir = os.path.join(_repo_root, "resources")
    ud_langs = get_ud_langs(resource_dir)

    excluded = []
    for lang in tqdm(sorted(ud_langs)):
        langcode = lang2langcode(lang)

        if has_um_coverage(langcode, resource_dir):
            continue

        # Default use_selected_treebanks=True, matching what the production
        # pipeline (sva_trees.pipeline, via word_order.process_treebank's
        # Treebank() calls) actually trains on -- e.g. Vietnamese is pinned
        # to UD_Vietnamese-VTB there via udlang2treebanks, so that's the
        # treebank whose feature coverage (or lack of it) explains the
        # pipeline's real output, even though a different, unused Vietnamese
        # treebank (UD_Vietnamese-TueCL) does carry some annotation.
        treebank = Treebank(
            lang.replace(" ", "_"),
            resource_dir=resource_dir,
            load_from_pickle=True,
            remove_typo=False,
            pickle_path="ud/ud_typo_pickles",
        )
        if treebank_has_feature_annotation(treebank):
            continue

        excluded.append((lang, langcode, len(treebank)))

    out_path = os.path.join(resource_dir, "langs_no_feats_no_um.txt")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(
            "# Languages excluded from UM/UM+UD coverage stats: the UD treebank\n"
            "# has zero morphological feature annotation on any token (so the\n"
            "# UD-derived UniMorph-schema fallback is necessarily empty -- see\n"
            "# multiblimp.ud2um.create_unimorph_from_ud), AND no proper UniMorph\n"
            "# (UM) data exists for the language either. 0% UM/UM+UD coverage for\n"
            "# these is expected, not a bug -- there is no inflectional data for\n"
            "# them anywhere in this project's resources.\n"
            "# Generated by scripts/find_no_coverage_langs.py\n"
            "# language\tlangcode\t#sentences_scanned\n"
        )
        for lang, langcode, n_sents in excluded:
            f.write(f"{lang}\t{langcode}\t{n_sents}\n")

    print(f"{len(excluded)} language(s) with no UD feature annotation and no UM coverage:")
    for lang, langcode, n_sents in excluded:
        print(f"  {lang}\t{langcode}\t{n_sents} sentences scanned")
    print(f"Written to {out_path}")


if __name__ == "__main__":
    main()
