"""Scan the local UD release checkout and report treebanks matching the five
"suspect" categories in multiblimp.treebank.flag_treebanks (the four local
flag types plus "code switching"): historical-language variants UD filed
under a modern language's folder instead of giving their own top-level
language, poetry-only treebanks, learner-essay treebanks, Twitter/tweet
treebanks, and code-switching treebanks. These are candidates a downstream
pipeline may want to exclude -- this script only reports them, it does not
filter anything itself.

Usage (from repo root or scripts/):
    python flag_treebanks_report.py

Writes resources/flagged_treebanks.txt.
"""
import os
import sys

_repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.append(os.path.join(_repo_root, "src"))

from multiblimp.treebank import flag_treebanks

FLAG_TYPES = ("old variant", "poetry only", "learner", "twitter", "code switching")


def main():
    resource_dir = os.path.join(_repo_root, "resources")

    rows = []
    for flag_type in FLAG_TYPES:
        results = flag_treebanks(flag_type, resource_dir=resource_dir)
        for language, treebanks in sorted(results.items()):
            for treebank in treebanks:
                rows.append((flag_type, language, treebank))

    out_path = os.path.join(resource_dir, "flagged_treebanks.txt")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(
            "# UD treebanks flagged by multiblimp.treebank.flag_treebanks as\n"
            "# candidates for exclusion. Report only -- nothing here is\n"
            "# filtered automatically.\n"
            "#\n"
            "# old variant   -- historical-language data UD filed as a treebank\n"
            "#                  within a modern language's folder (e.g.\n"
            "#                  UD_Swedish-Old) rather than as its own top-level\n"
            "#                  Old_X language (e.g. UD_Old_English-Cairo, not\n"
            "#                  flagged).\n"
            "# poetry only   -- README Genre: field is exclusively \"poetry\".\n"
            "# learner       -- README Genre: field includes \"learner-essays\".\n"
            "# twitter       -- \"twitter\"/\"tweet\" appears in the README's\n"
            "#                  Summary section.\n"
            "# code switching -- README describes the text as code-switched\n"
            "#                  (outside the Changelog section, and not paired\n"
            "#                  with \"removed\"/\"excluded\" in the same sentence).\n"
            "#\n"
            "# Generated by scripts/flag_treebanks_report.py\n"
            "# flag_type\tlanguage\ttreebank\n"
        )
        for flag_type, language, treebank in rows:
            f.write(f"{flag_type}\t{language}\t{treebank}\n")

    print(f"{len(rows)} flagged treebank(s):")
    for flag_type in FLAG_TYPES:
        matches = [r for r in rows if r[0] == flag_type]
        print(f"  {flag_type}: {len(matches)}")
        for _, language, treebank in matches:
            print(f"    {language}\t{treebank}")
    print(f"Written to {out_path}")


if __name__ == "__main__":
    main()
